version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    - image: circleci/mysql:5.7.21
      environment:
        MYSQL_USER: root

    working_directory: /go/src/github.com/lab259/go-worker-pool
    steps:
      - checkout

      - run: go get -u github.com/onsi/ginkgo/ginkgo
      - run: make deps-ci
      - run: make test
      - run: make coverage-ci
      - run: bash <(curl -s https://codecov.io/bash)
